version: '3.3'

services:
   # Database
   db:
     image: mysql:8.0
     volumes:
       - db_data:/var/lib/mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpresswithdocker
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpresswithdocker
       MYSQL_PASSWORD: wordpresswithdocker
     networks:
       - wpsite

   # PhpMyAdmin
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     ports:
       - 8080:80
     environment:
       - PMA_ARBITRARY=1
     networks:
        - wpsite

   # WordPress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpresswithdocker
       WORDPRESS_DB_PASSWORD: wordpresswithdocker
       WORDPRESS_DB_NAME: wordpress
     networks:
       - wpsite
networks:
    wpsite:
volumes:
    db_data: {}
